### ISSUE TITLE
`cargo doc` fails if lending-iterator is depended on with `default-features = false`

### ISSUE THREAD

**Issue by VorpalBlade** [danielhenrymantilla/lending-iterator.rs#11]
I have the following dependency in my `Cargo.toml`: 

```toml
lending-iterator = { version = "0.1.6", default-features = false }
```

When I run `cargo doc` all the dependencies docs are built (not just my own crate). This result in the following error however:

```
error[E0433]: failed to resolve: could not find `alloc` in the list of imported crates
 --> /home/arvid/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lending-iterator-0.1.6/src/lending_iterator/dyn/tests.rs:3:7
  |
3 |     ::alloc::{
  |       ^^^^^ could not find `alloc` in the list of imported crates

error: Compilation failed, aborting rustdoc
```

**Comment by danielhenrymantilla** [comment]
Thanks for pointing it out: this is fixed as of #12, which will be released as `0.1.7`.

  - For what is worth, by the way, you could add the `--no-deps` flag to `cargo doc`, not only to dodge this bug in the meantime, but also to, more generally, speed up `cargo doc` (it is however, less suitable for fully offline scenarios, since you won't have access to the https://docs.rs-backed fallback) 🙂
